version: 1.0.{build}
image: Visual Studio 2017
install:  
  - ps: nuget restore GnuPlotSharp.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal


-
  branches:
    only:
      - master
-
  branches:
    only:
      - release
    deploy:
    - provider: NuGet
      api_key:
        secure: Z1DoV4FAaop88LOqNhOuUf+SUrJtH2toXU5Kx++tXpJLAYWluu4ppfdbF+SUT+7+